### ISSUE TITLE
getImeiForSlot issue showing

### ISSUE THREAD

**Issue by appasaheb4** [SimenCodes/react-native-imei#22]
![Screenshot_1598264338](https://user-images.githubusercontent.com/24726539/91033691-6f124900-e621-11ea-8e2c-fb742eef9829.png)

**Comment by SimenCodes** [comment]
Hi! To help you, I would need to know more about what goes wrong.

Can you post the Android log for when this happens? (`adb logcat`) It usually contains additional information that could be very helpful. Also, what does your `AndroidManifest.xml` file look like?

**Comment by TrustDec** [comment]
E/unknown:ReactNative: Exception in native call
    java.lang.SecurityException: getImeiForSlot: The user 10133 does not meet the requirements to access device identifiers.
        at android.os.Parcel.createException(Parcel.java:2071)
        at android.os.Parcel.readException(Parcel.java:2039)
        at android.os.Parcel.readException(Parcel.java:1987)
        at com.android.internal.telephony.ITelephony$Stub$Proxy.getImeiForSlot(ITelephony.java:10419)
        at android.telephony.TelephonyManager.getImei(TelephonyManager.java:1720)
        at com.mobileintegration.imei.RNImeiModule.getImei(RNImeiModule.java:44)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:919)

**Comment by SimenCodes** [comment]
This sounds like your app doesn't fullfil the requirements to access device IDs in recent Android versions. See https://developer.android.com/about/versions/10/privacy/changes#non-resettable-device-ids and #20 for more information. Feel free to reopen if this is not the case.
